# SPDX-FileCopyrightText: 2024-2025 Temple University <kleinweb@temple.edu>
# SPDX-License-Identifier: CC0-1.0

from_latest_tag = false
ignore_merge_commits = true
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
branch_whitelist = []
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = ["just check", "just release::bump '{{latest}}' {{version}}"]
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []

[changelog]
template = "remote"
remote = "github.com"
owner = "kleinweb"
repository = "user-profile-block"
path = "CHANGELOG.md"
authors = [
  { signature = "Chris Montgomery", username = "montchr" },
  { signature = "Bella Pezzati", username = "bpizzle" },
]

[git_hooks]
[commit_types]
[bump_profiles]
[packages]
