# SPDX-FileCopyrightText: (C) 2025-2026 Temple University <kleinweb@temple.edu>
# SPDX-License-Identifier: CC0-1.0

version = 1

# Files that cannot have embedded headers
[[annotations]]
path = [
  "**.json",
  "**.lock",
  "**.properties",
  "**.d.ts",
  "**/.ignore",
  "**/.rgignore",
  ".rgignore",
  "**/.gitattributes",
  "**/.gitignore",
  "**/.gitkeep",
  ".config/org_id",
]
SPDX-FileCopyrightText = "(C) 2025-2026 Temple University <kleinweb@temple.edu>"
SPDX-License-Identifier = "CC0-1.0"

# Build artifacts (generated, binary-like)
[[annotations]]
path = ["public/build/**"]
SPDX-FileCopyrightText = "(C) 2025-2026 Temple University <kleinweb@temple.edu>"
SPDX-License-Identifier = "GPL-2.0-or-later"
