# SPDX-FileCopyrightText: (C) 2025 Temple University <kleinweb@temple.edu>
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = ["**.blade.php"]
SPDX-FileCopyrightText = "(C) 2025 Temple University <kleinweb@temple.edu>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [
  "**.json",
  "**.lock",
  "**.properties",
  "**.yml",
  "**.d.ts",
  "**/.ignore",
  "**/.gitattributes",
  "**/.gitignore",
  "**/.gitkeep",
  ".config/org_id",
]
SPDX-FileCopyrightText = "(C) 2025 Temple University <kleinweb@temple.edu>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["**.md", "**.org", "**.txt"]
SPDX-FileCopyrightText = "(C) 2025 Temple University <kleinweb@temple.edu>"
SPDX-License-Identifier = "CC-BY-NC-SA-4.0"
